### ISSUE TITLE
How do I use this tool?

### ISSUE THREAD

**Issue by terryxxxxx** [sylym/comfy_vid2vid#1]
I don't know which folder to put it in, and I don't know how to start this node.

**Comment by sylym** [comment]
You can install the plug-in by running the following command
```
cd ComfyUI/custom_nodes
git clone https://github.com/sylym/comfy_vid2vid
cd comfy_vid2vid
python -m pip install -r requirements.txt
```
For ComfyUI portable standalone build, you need to replace the last command line with the following command
```
..\..\..\python_embeded\python.exe -m pip install -r requirements.txt
```
The names of all new nodes end with sequence.

Note: The plug-in is currently in the testing phase, and unexpected bugs may occur. I will add detailed instructions when it is officially released.

**Comment by sylym** [comment]
The plug-in is officially released.
