### ISSUE TITLE
Need to update. due to the ComfyUI's lora structure is changes.

### ISSUE THREAD

**Issue by ltdrdata** [sylym/comfy_vid2vid#7]
https://github.com/sylym/comfy_vid2vid/blob/main/sd.py#L3-L3

'model_lora_keys' is changed to 'model_lora_keys_clip'

**Comment by davechilds** [comment]
There is also a model_lora_keys_unet in the comfy sd.py - initially seems to be remedied by changing line 3 in your sd.py to 

from comfy.sd import load_model_weights, ModelPatcher, VAE, CLIP, model_lora_keys_clip, model_lora_keys_unet

**Comment by sylym** [comment]
fixed
